name: clone_sns_insta
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.9.3
  expandable_text: ^2.3.0
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_storage: ^11.3.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  photo_manager: ^2.7.1
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/